image: java:8-jdk

stages:
- build
- deploy

desktop:
  stage: build
  script:
  - ./gradlew desktop:dist
  artifacts:
    expire_in: 31d
    paths:
    - exmatrikulatortd/desktop/build/libs/

pages:
  stage: deploy
  image: alpine:latest
  script:
  - mv html/build/dist/ public/
  artifacts:
    paths:
    - public/
  only:
  - master
