image: gradle:alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"


before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - cd exmatrikulatortd/
  - chmod +x ./gradlew


stages:
  - build
  - test

build:
  stage: build
  script:
    - gradlew desktop:run
    
unitTests:
  stage: test
  script:
    - ./exmatrikulatortd/gradlew test