image: openjdk:8-jdk

stages:
  - build
  - test

build:
  stage: build
  script:
    - ./exmatrikulatortd/gradlew clean build
    
unitTests:
  stage: test
  script:
    - ./exmatrikulatortd/gradlew test