image: gradle:alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"


before_script:
  - cd exmatrikulatortd/


stages:
  - build
  - test

build:
  stage: build
  script:
  - ./gradlew desktop:dist
  - mv desktop/build/libs/ ../jars/
  artifacts:
    paths:
      - jars
    
unitTests:
  stage: test
  artifacts:
    paths:
    - report
  script:
    - ./gradlew test
    - ./gradlew check jacocoTestReport 
    - mv core/build/reports/jacacoco/test/ ../report/
    - cat ../report/index.html
