image: gradle:alpine

stages:
  - build
  - test

build:
  stage: build
  script:
    - cd exmatrikulatortd/
    - gradlew desktop:run
    
unitTests:
  stage: test
  script:
    - ./exmatrikulatortd/gradlew test