image: gradle:alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"


before_script:
  - cd exmatrikulatortd/


stages:
  - build
  - test

build:
  stage: build
  script:
  - ./gradlew desktop:dist
  - ls -R
  artifacts:
    paths:
      - exmatrikulatortd/desktop/build/libs/desktop-1.0.jar
    
unitTests:
  stage: test
  script:
    - ./gradlew test