image: gradle:alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"


before_script:
  - cd exmatrikulatortd/


stages:
  - build
  - test

build:
  stage: build
  script:
  - ./gradlew desktop:dist
    
unitTests:
  stage: test
  script:
    - gradlew desktop:test