image: gradle:alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"


before_script:
  - cd exmatrikulatortd/


stages:
  - build
  - test

build:
  stage: build
  script:
  - ./gradlew desktop:dist
  artifacts:
    paths:
      - exmatrikulatortd/desktop/build/libs/*
    
unitTests:
  stage: test
  script:
    - ./gradlew test
  artifacts:
    paths:
      - exmatrikulatortd/core/build/reports/tests/test/*